upstream call_me_ai_servers {
    server 127.0.0.1:10040;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name domovoice.ai www.domovoice.ai;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name domovoice.ai www.domovoice.ai;

    ssl_certificate /etc/letsencrypt/live/domovoice.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domovoice.ai/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/domovoice.ai/chain.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    client_max_body_size 25M;
    client_body_timeout 120;
    client_header_timeout 120;
    keepalive_timeout 120;

    access_log /var/log/call_me_ai_nginx_access.log;
    error_log /var/log/call_me_ai_nginx_error.log;

    location /ws/ {
    	proxy_pass http://call_me_ai_servers;
  	proxy_http_version 1.1;
    
    	# Правильные заголовки для Upgrade
    	proxy_set_header Upgrade $http_upgrade;
  	  proxy_set_header Connection "Upgrade";
    
    	# Отключаем буферизацию и кэш (теперь синтаксис верный)
   	 proxy_buffering off;
  	  proxy_cache off;
    
    	# Таймауты, чтобы соединение не рвалось при молчании
    	proxy_read_timeout 3600s;
    	proxy_send_timeout 3600s;

    	# Стандартные заголовки
    	proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        # auth_basic "Restricted";
        # auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://call_me_ai_servers;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/idurnev/apps/call_me_ai/static/;
    }
}
