[program:call_me_ai]
directory=/home/idurnev/apps/call_me_ai
user=idurnev
group=idurnev

#command=/bin/bash -lc 'set -a; source /home/idurnev/apps/call_me_ai/.env; set +a; exec /home/idurnev/apps/call_me_ai/venv/bin/gunicorn -w 2 --timeout 240 -b 127.0.0.1:10040 run:app'
#command=/bin/bash -lc 'set -a; source /home/idurnev/apps/call_me_ai/.env; set +a; exec /home/idurnev/apps/call_me_ai/venv/bin/gunicorn -w 1 -k gevent --timeout 240 -b 127.0.0.1:10040 run:app'
command=/bin/bash -lc 'set -a; source /home/idurnev/apps/call_me_ai/.env; set +a; exec /home/idurnev/apps/call_me_ai/venv/bin/gunicorn -w 1 -k eventlet --timeout 3600 -b 127.0.0.1:10040 run:app'

autostart=true
autorestart=true
startsecs=5
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true

stdout_logfile=/var/log/supervisor/call_me_ai.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/log/supervisor/call_me_ai.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

environment=PYTHONUNBUFFERED="1"
